version: "2.0"
services:
    super_fit_db:
        image: postgres
        container_name: super_fit_db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        ports:
            - 5432:${DB_PORT}
